Dfe.SchoolAccount.Web/Models/CardViewModel.cs
namespace Dfe.SchoolAccount.Web.Models;

public sealed class CardViewModel
{
    public string Heading { get; set; } = null!;

    public string Summary { get; set; } = null!;

    public string LinkUrl { get; set; } = null!;
}

Dfe.SchoolAccount.Web/Models/Content/Cards/ExternalResourceCardContent.cs
namespace Dfe.SchoolAccount.Web.Models.Content.Cards;

public sealed class ExternalResourceCardContent
{
    public string Heading { get; set; } = null!;

    public string Summary { get; set; } = null!;

    public string LinkUrl { get; set; } = null!;
}

Dfe.SchoolAccount.Web/Models/Partials/CardsPartialViewModel.cs
namespace Dfe.SchoolAccount.Web.Models.Partials;

using Dfe.SchoolAccount.Web.Models.Content;

/// <summary>
/// View model for the "Partials/_Cards" partial view.
/// </summary>
public sealed class CardsPartialViewModel
{
    /// <summary>
    /// Gets or sets the heading level used for each card.
    /// </summary>
    /// <remarks>
    /// <para>Defaults to a value of 2 to produce <c>&lt;h2&gt;</c> elements.</para>
    /// </remarks>
    public int HeadingLevel { get; set; } = 2;

    /// <summary>
    /// Gets or sets the number of columns which cards should be arranged within.
    /// </summary>
    /// <remarks>
    /// <para>Defaults to a value of 3.</para>
    /// </remarks>
    public int ColumnCount { get; set; } = 3;

    /// <summary>
    /// Gets or sets the collection of cards that will be presented in the partial view.
    /// </summary>
    public IEnumerable<CardModel> Cards { get; set; } = Array.Empty<CardModel>();
}

Dfe.SchoolAccount.Web/ViewComponents/FooterNavigationViewComponent.cs
namespace Dfe.SchoolAccount.Web.ViewComponents;

using Dfe.SchoolAccount.Web.Models.Components;
using Dfe.SchoolAccount.Web.Services.Content;
using Microsoft.AspNetCore.Mvc;

public sealed class FooterNavigationViewComponent : ViewComponent
{
    private readonly IWebsiteGlobalsFetcher websiteGlobalsFetcher;

    public FooterNavigationViewComponent(IWebsiteGlobalsFetcher websiteGlobalsFetcher)
    {
        this.websiteGlobalsFetcher = websiteGlobalsFetcher;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var websiteGlobals = await this.websiteGlobalsFetcher.FetchWebsiteGlobalsAsync();

        var model = new FooterNavigationViewModel {
            Links = websiteGlobals.FooterLinks,
        };

        return this.View(model);
    }
}

Dfe.SchoolAccount.Web/ViewComponents/SiteTitleViewComponent.cs
namespace Dfe.SchoolAccount.Web.ViewComponents;

using Dfe.SchoolAccount.Web.Models.Components;
using Dfe.SchoolAccount.Web.Services.Content;
using Microsoft.AspNetCore.Mvc;

public sealed class SiteTitleViewComponent : ViewComponent
{
    private readonly IWebsiteGlobalsFetcher websiteGlobalsContentFetcher;

    public SiteTitleViewComponent(
        IWebsiteGlobalsFetcher websiteGlobalsContentFetcher)
    {
        this.websiteGlobalsContentFetcher = websiteGlobalsContentFetcher;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var websiteGlobals = await this.websiteGlobalsContentFetcher.FetchWebsiteGlobalsAsync();

        var model = new SiteTitleViewModel {
            SiteTitle = websiteGlobals.SiteTitle,
        };

        return this.View(model);
    }
}

Dfe.SchoolAccount.Web/Views/Shared/Partials/_Cards.cshtml
@using Dfe.SchoolAccount.Web.Models.Partials;

@model CardsPartialViewModel

@foreach (var cardRow in Model.Cards.ArrangeIntoGroupsOf(Model.ColumnCount))
{
    <div class="app-card-grid govuk-grid-row govuk-!-margin-bottom-7">
        @foreach (var card in cardRow)
        {
            var cardSummaryId = ViewHelpers.GetUniqueIdentifier();

            <div class="app-card-grid__column govuk-grid-column-one-third card-container">
                <section class="app-card" aria-describedby="@cardSummaryId">
                    @Html.Raw($"<h{ Model.HeadingLevel } class=\"app-card__title govuk-heading-m\">")
                    @if (!string.IsNullOrEmpty(card.LinkUrl))
                    {
                        <a class="app-card__link govuk-link" href="@card.LinkUrl">@card.Heading</a>
                    }
                    else
                    {
                        @card.Heading
                    }
                    @Html.Raw($"</h{ Model.HeadingLevel }>")
                    <div class="app-card__summary" id="@cardSummaryId">
                        @{
                            var trimmedParagraphs = card.Summary.Split('\n', '\r')
                                .Select(para => para.Trim())
                                .Where(para => !string.IsNullOrEmpty(para));
                        }
                        @foreach (var summaryParagraph in trimmedParagraphs)
                        {
                            <p>@summaryParagraph</p>
                        }
                    </div>
                </section>
            </div>
        }
    </div>
}

Dfe.SchoolAccount.Web/Views/Shared/Partials/_DfeHeaderPartial.cshtml
@using GovUk.Frontend.AspNetCore

@inject IViewLocalizer ViewLocalizer

<header class="app-header " role="banner">
    <div class="app-header__container">
        <div class="app-header__logo">
            <a class="app-header__link app-header__link--service " href="/" aria-label="@ViewLocalizer["LogoAlt"]">
                <img src="~/images/dfe-logo.png" class="app-header__logo-image" alt="@ViewLocalizer["LogoAlt"]">
                <img src="~/images/dfe-logo-alt.png" class="app-header__logo-image--hover" alt="@ViewLocalizer["LogoAlt"]">
                <span class="app-header__service-name">
                    @await Component.InvokeAsync("SiteTitle")
                </span>
            </a>
        </div>
        <div class="app-header__content" id="content-header">
            <div class="app-header__username">
                @if (User.Identity?.IsAuthenticated == true)
                {
                    <a class="govuk-link govuk-link--inverse" href="/account/sign-out">@ViewLocalizer["SignOutPrompt"]</a>
                }
                else
                {
                    <a class="govuk-link govuk-link--inverse" href="/home">@ViewLocalizer["SignInPrompt"]</a>
                }
            </div>
        </div>
    </div>
</header>

Dfe.SchoolAccount.Web/Views/Shared/Partials/_FooterPartial.cshtml
@using GovUk.Frontend.AspNetCore

@inject IViewLocalizer ViewLocalizer

<footer class="govuk-footer " role="contentinfo">
    <div class="govuk-width-container ">
        <div class="govuk-footer__meta">
            <div class="govuk-footer__meta-item govuk-footer__meta-item--grow">
                <h2 class="govuk-visually-hidden">@ViewLocalizer["SupportLinksHeading"]</h2>
                @await Component.InvokeAsync("FooterNavigation")
                <svg aria-hidden="true"
                        focusable="false"
                        class="govuk-footer__licence-logo"
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 483.2 195.7"
                        height="17"
                        width="41">
                    <path fill="currentColor"
                            d="M421.5 142.8V.1l-50.7 32.3v161.1h112.4v-50.7zm-122.3-9.6A47.12 47.12 0 0 1 221 97.8c0-26 21.1-47.1 47.1-47.1 16.7 0 31.4 8.7 39.7 21.8l42.7-27.2A97.63 97.63 0 0 0 268.1 0c-36.5 0-68.3 20.1-85.1 49.7A98 98 0 0 0 97.8 0C43.9 0 0 43.9 0 97.8s43.9 97.8 97.8 97.8c36.5 0 68.3-20.1 85.1-49.7a97.76 97.76 0 0 0 149.6 25.4l19.4 22.2h3v-87.8h-80l24.3 27.5zM97.8 145c-26 0-47.1-21.1-47.1-47.1s21.1-47.1 47.1-47.1 47.2 21 47.2 47S123.8 145 97.8 145" />
                </svg>
                <span class="govuk-footer__licence-description">
                    @Html.Raw(ViewLocalizer["LicenseHtml"].Value)
                </span>
            </div>
            <div class="govuk-footer__meta-item">
                <a class="govuk-footer__link govuk-footer__copyright-logo"
                    href="https://www.nationalarchives.gov.uk/information-management/re-using-public-sector-information/uk-government-licensing-framework/crown-copyright/">© Crown copyright</a>
            </div>
        </div>
    </div>
</footer>